### ISSUE TITLE
Read only property for ServerObjectManager nextNetworkId

### ISSUE THREAD

**Issue by emrys90** [MirageNet/Mirage#1082]
**Please explain the suggested feature in detail.**
Adding a read only property for what the next NetId that would be assigned to a spawned object.

**How exactly does this keep you from releasing your game right now?**
I use network id's as a form of ownership check on clients, and being able to access the net id before spawning so that its part of initial payload is ideal.

**Comment by James-Frowen** [comment]
You can create a very simple `NetIdGenerator` and set the field on `ServerObjectManager`. And then add the Next Id a public field on that.

Would be better to use a custom `NetIdGenerator` instead of add a getter for next id. The property would only be able to give the next ID if using the default ids but not if using Generator.
