### ISSUE TITLE
Mirage/Weaver reports line (0, 0) when throwing error about incorrect [NetworkMessage] usage

### ISSUE THREAD

**Issue by Xaer033** [MirageNet/Mirage#632]
I ran into an issue when accidentally adding a NetworkMessage attribute where I shouldn't have (a superclass of NetworkManager). In the editor, I get the error:

`(0,0): error Cannot generate reader for component type TestNetworkManager. Use a supported type or provide a custom reader (at TestNetworkManager)`

The error makes perfect sense, I don't want network manager to be a network message :P
But the line number made this a little more difficult to track down. I ran into this while converting my project from Mirror -> Mirage, and had assumed that one of my network Message structs was trying to send a NetworkManager for some reason. Took me a little while to find out I fat fingered the attribute on the NetworkManager class itself 🥇 .

**Repro project**

Test project showing issue: https://drive.google.com/file/d/1AKAs01A8nRSBRYAZ5XEwmTHeTA7mZLdA/view?usp=sharing
Though this should be fairly easy to repro, even without the project. Just add the [NetworkMessage] above any class that is a super of NetworkManager.

**To Reproduce**
1. Open the attached project
2. ???
3. Profit.

**Expected behavior**
Throw the error message, like before, but maybe with the correct line numbers? Maybe it is a limitation with weaver, but I figure this might come up again in a non-fat-fingered case for someone. Having the File/line number straight away could help fix any user issues that come up 👍  

**Screenshots**
eh, its just a console/Unity compile error mentioned above

**Desktop (please complete the following information):**
* OS: Windows
* Build target: Editor
* Unity version: 2020.2.3f1
* Mirage version `66.2.1` and above

**Additional context**
I think we good, if you need any more info, let me know!

**Comment by paulpach** [comment]
I agree.  Believe me,  I tried to.   

The problem is the .net file format.  It _only_ stores line numbers for method bodies,  it does not store line numbers for fields, classes, attributes or anything else.  The C# compiler simply does not generate it.  

This means there is no way to get this information in the weaver. 
Here is a conversation with JB Evain about this:
https://mono-cecil.narkive.com/wcPVkTlL/determining-line-number-of-field-declaration-from-pdb

Best I can do is just not display (0,0) at all

**Comment by Xaer033** [comment]
Gotcha, that makes sense, just thought I would note it 👍 
Want me to close the issue?
