### ISSUE TITLE
Benchmark / Performance Documentation

### ISSUE THREAD

**Issue by remiteeple** [MirageNet/Mirage#994]
**Please explain the suggested feature in detail.**
Looking to see a more fine grain comparison between existing networking solutions.  At the very least a benchmark displaying performance would be fantastic.

**How exactly does this keep you from releasing your game right now?**
I'm not convinced that I should switch to Mirage from Mirror yet, if the performance is equal or improved even slightly then I'd more heavily consider making the switch.

**Can you suggest a possible solution?**
Add benchmark performance and/or comparisons to the readme or documentation.  Alternatively include a version of Mirror's benchmark translated to MirageNet as an example.

**Additional context**

**Comment by James-Frowen** [comment]
I'll try do some benchmarking this week and post the results here

**Comment by remiteeple** [comment]
> I'll try do some benchmarking this week and post the results here

Fantastic!  Thanks for the quick response.

**Comment by James-Frowen** [comment]
Just to keep this updated, I've got some initial results. 

Mirage seems to be doing a lot better, which is surprising because I was still testing with the current NetworkTransform which isn't they good.

Here's some links to rough results so far:
[benchmark repo](https://github.com/James-Frowen/NetworkingBenchmarkNov21)(see branches for mirror)
[Spreadsheet](https://docs.google.com/spreadsheets/d/1wuDpd6h5YiVGkhS_trj3IxQdeccWfJZSNIiSicFFUwk/edit?usp=sharing)

and as a bonus [differences between mirror and mirage](
https://github.com/James-Frowen/NetworkingBenchmarkNov21/compare/643649c297c2988a25b126467243295882665224..55314d4dabbf6fdbc233559ffbcf8a0d73fd151d)

**Comment by remiteeple** [comment]
Hey this is excellent!  
This is exactly the information I was looking for.  I'll propose the spreadsheet information and advantages to my uppers to see if we can't transition at some point in the future.
Thanks!
